# Generated by Django 3.2.25 on 2025-12-17 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import patients.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique identifier for the device', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name for the device', max_length=100)),
                ('device_type', models.CharField(choices=[('spectrometer', 'Spectrometer'), ('sensor', 'Sensor'), ('other', 'Other')], default='spectrometer', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the device is active and available for use')),
                ('description', models.TextField(blank=True, help_text='Device description and specifications')),
                ('location', models.CharField(blank=True, help_text='Physical location of the device', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='patients.device')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Doctor'), ('technician', 'Lab Technician'), ('staff', 'Staff')], default='staff', max_length=20)),
                ('is_admin', models.BooleanField(default=False, help_text='User has admin privileges')),
                ('phone', models.CharField(blank=True, help_text='Contact number', max_length=20)),
                ('department', models.CharField(blank=True, help_text='Department or specialty', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devices', models.ManyToManyField(blank=True, help_text='Devices this user has access to', related_name='assigned_users', to='patients.Device')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='SpectralPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wavelength', models.FloatField()),
                ('intensity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectra', to='patients.measurementsession')),
            ],
            options={
                'ordering': ['wavelength'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(default=patients.models.generate_patient_id, editable=False, help_text='Unique identifier for the patient', max_length=10, unique=True, verbose_name='Patient ID')),
                ('name', models.CharField(help_text='Full name of the patient', max_length=200)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth (YYYY-MM-DD)', null=True, verbose_name='Date of Birth')),
                ('age', models.PositiveIntegerField(blank=True, help_text='Age in years', null=True, verbose_name='Age')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('', 'Prefer not to say')], help_text='Gender identity', max_length=1)),
                ('phone_number', models.CharField(blank=True, help_text='Contact number with country code', max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, help_text='Primary email address', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Full postal address')),
                ('clinical_notes', models.TextField(blank=True, help_text='Medical history and clinical observations', verbose_name='Clinical Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.device')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='measurementsession',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='patients.patient'),
        ),
    ]
