# Generated by Django 3.2.25 on 2025-12-11 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(blank=True, max_length=128)),
                ('completed', models.BooleanField(default=False)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(help_text='Unique identifier for the patient', max_length=64, unique=True, verbose_name='Patient ID')),
                ('name', models.CharField(help_text='Full name of the patient', max_length=200)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth (YYYY-MM-DD)', null=True, verbose_name='Date of Birth')),
                ('age', models.PositiveIntegerField(blank=True, help_text='Age in years', null=True, verbose_name='Age')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('', 'Prefer not to say')], help_text='Gender identity', max_length=1)),
                ('phone_number', models.CharField(blank=True, help_text='Contact number with country code', max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, help_text='Primary email address', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Full postal address')),
                ('clinical_notes', models.TextField(blank=True, help_text='Medical history and clinical observations', verbose_name='Clinical Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpectralPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wavelength', models.FloatField()),
                ('intensity', models.FloatField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectra', to='patients.measurementsession')),
            ],
            options={
                'ordering': ['wavelength'],
            },
        ),
        migrations.AddField(
            model_name='measurementsession',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='patients.patient'),
        ),
    ]
