# Generated by Django 3.2.25 on 2025-12-12 17:14

from django.db import migrations, models
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default=patients.models.generate_patient_id, editable=False, help_text='Unique identifier for the patient', max_length=10, unique=True, verbose_name='Patient ID'),
        ),
    ]
