# Generated by Django 3.2.25 on 2025-12-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='special_notes',
            field=models.TextField(blank=True, help_text='Special notes or important information about the patient', null=True, verbose_name='Special Notes'),
        ),
    ]
