# Generated by Django 3.2.25 on 2025-12-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_special_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='special_notes',
        ),
    ]
