# Generated by Django 3.2.25 on 2025-12-15 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_patient_special_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementsession',
            name='device_id',
            field=models.CharField(default='001', max_length=128),
        ),
        migrations.AlterField(
            model_name='measurementsession',
            name='session_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
